### ISSUE TITLE
เมื่อลบจำนวนตั๋วออกเป็นค่าว่างแล้วกดซื้อจะได้ NaN ออกมา สามารถปรับปรุง code ส่วนนี้ได้ยังไงบ้างคะ

### ISSUE THREAD

**Issue by RSuwanwatin** [Pathompob/exercise#1]
![screen shot 2561-09-19 at 00 49 04](https://user-images.githubusercontent.com/8394464/45707490-394cc600-bba9-11e8-920b-88659f0faf30.png)

**Comment by Pathompob** [comment]
Check Value ใน event onClick
<img width="486" alt="screen shot 2561-09-19 at 04 56 13" src="https://user-images.githubusercontent.com/26622866/45718811-8b511400-bbc8-11e8-864b-8a52809bdff2.png">
